---
title: ""
output: 
  flexdashboard::flex_dashboard:
    theme: readable
    logo: game1.png
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library (tidyverse)
library(plotly)
library(RColorBrewer)
library(wesanderson)
# ----------------------------------------------------------------------------------------------------
# Lectura del dataset 1: tiempo_pantalla
# ----------------------------------------------------------------------------------------------------
tiempo_pantalla <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-04-17/tiempo_pantalla.csv")
View(tiempo_pantalla)
# ----------------------------------------------------------------------------------------------------
#limpieza inicial
tiempo_pantallaSinNA <-na.omit(tiempo_pantalla)
View(tiempo_pantallaSinNA)
# ----------------------------------------------------------------------------------------------------
# selecciono los primeros 10 personajes con mayor cantidad de minutos en pantalla
# ----------------------------------------------------------------------------------------------------
primeros10 <- filter(tiempo_pantallaSinNA, (tiempo_pantallaSinNA$minutos_pantalla>103))
View(primeros10)
# ----------------------------------------------------------------------------------------------------
#visualizo los últimos valores de la tabla
tail(tiempo_pantallaSinNA)   
# selecciono los últimos 10 personajes con menor cantidad de minutos en pantalla
ultimos10 <- filter(tiempo_pantallaSinNA, (tiempo_pantallaSinNA$minutos_pantalla<2.30))
View(ultimos10)
# ----------------------------------------------------------------------------------------------------
# Lectura del dataset 2:personajes_libros
# ---------------------------------------------------------------------------------------------------- 
personajes_libros <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-04-17/personajes_libro.csv")
View(personajes_libros)
genero <- as.factor(personajes_libros$genero)
View(genero)
# agrupo por lealtad y cuento la cantidad de hombres y mujeres
generoporlealtad <-personajes_libros %>% group_by(lealtad) %>% count(genero)                 
View (generoporlealtad)
# Para los registros que no tienen ninguna lealtad reemplazo la descripción por "No pertenece a ninguna casa noble"
generoporlealtad[generoporlealtad$lealtad == "Ninguna",1]<-"No pertenece a ninguna casa noble"
#renombro las columnas
names (generoporlealtad) =c("lealtad", "genero","totalXgenero")
View(generoporlealtad)

```

Row {data-height=650}
-----------------------------------------------------------------------

### Total de Personajes por género correspondiente a cada casa noble

```{r}
# ---------------------------------------------------------------------------------------------------------------- 
#Gráfico con plotly: Total de Personajes por género correspondiente a cada casa noble
# -----------------------------------------------------------------------------------------------------
p<- plot_ly (x = generoporlealtad$lealtad, y = generoporlealtad$totalXgenero, color = generoporlealtad$genero, 
text= paste('Lealtad','',generoporlealtad$lealtad,":",generoporlealtad$totalXgenero), 
         hoverinfo = "text", type = "bar") %>% layout(title= '', 
                                                      label.legend= 'Personaje',
                                                      xaxis = list(showline = F, 
                                                                   showticklabels = F, 
                                                                   fixedrange = T,
                                                                   showlegend =TRUE,
                                                                   title = "Casa Noble"),
                                                      yaxis = list(fixedrange = T, 
                                                                   title = ""))
p
```

Row {data-height=350}
-----------------------------------------------------------------------

###  Personajes con menor cantidad de minutos en pantalla

```{r}
# ---------------------------------------------------------------------------------------------------------------- 
#Primer gráfico con ggplot2: Personajes con menor cantidad de minutos en pantalla
# -----------------------------------------------------------------------------------------------------
pal <- wes_palette("Darjeeling1", 10, type = "continuous")

p<- ggplot(data=ultimos10, aes(x=nombre, y=minutos_pantalla), colour=nombre) + geom_col(aes(fill=nombre))
p +  labs(x = "Personajes", y = "Tiempo (min)", colour = " Personajes", 
          title = "Personajes con menor protagonismo",
          subtitle = "Temporada de 1 a 6")+ 
  scale_fill_manual(values=pal)+ scale_x_discrete(limits=c("Ilyn Payne","Ternesio Terys","Quaithe", "Hugh of the Vale", "Rorge",
                                                             "Tickler", "Mhaegen","Biter", "Lhara", "Tobho Mott"))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust=1, color="black"))+  
  theme(plot.title = element_text(family="Courier",
                                  size=rel(1.5),        
                                  vjust=2,                                                    
                                  hjust= 0.5,
                                  position_identity(center),   
                                  face="bold",      #Tipo: Letra negra, otras posibilidades son "plain", "italic", "bold" y "bold.italic
                                  color="darkgreen",        #Color del título: maroon, lightblue, lightblue,darkblue, darkorange, black.
                                  lineheight=2.0),  legend.position= "", legend.text = element_blank())
```

### Personajes con mayor cantidad de minutos en pantalla

```{r}
# ---------------------------------------------------------------------------------------------------------------- 
#Segundo gráfico con ggplot2: Personajes con mayor cantidad de minutos en pantalla
# -----------------------------------------------------------------------------------------------------
pal <- wes_palette("Rushmore1", 10, type = "continuous")                     #paletas preferidas: Rushmore1,GrandBudapest1, Darjeeling2
p<- ggplot(data=primeros10, aes(x=nombre, y=minutos_pantalla), colour=nombre) + geom_col(aes(fill=nombre))+
  labs(x = "Personajes", y = "Tiempo (min)", colour = " Personajes", 
          title = "Personajes con mayor protagonismo ",
          subtitle = "Temporada de 1 a 6")+
  scale_fill_manual(values=pal)+ scale_x_discrete(limits=c("Tyrion Lannister","Jon Nieve","Daenerys Targaryen", "Cersei Lannister", "Sansa Stark", "Arya Stark",
                                                           "Jaime Lannister","Theon Greyjoy", "Samwell Tarly", "Jorah Mormont"))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust=1, color="black"))+ 
  theme(plot.title = element_text(family="Courier",
                                  size=rel(1.5),        
                                  vjust=2, 
                                  hjust= 0.5, 
                                  position_identity(center),   
                                  face="bold",       #Tipo: Letra negra, otras posibilidades son "plain", "italic", "bold" y "bold.itali
                                  color="darkred",   #Color del título: maroon, lightblue, lightblue,darkblue, darkorange, black.
                                  lineheight=2.0), legend.position= "", legend.text = element_blank())
p

```

