---
title: "Juego de Tronos"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library (tidyverse)
#install.packages("viridis")  # Install
#library("viridis")  
library(plotly)
library(wesanderson)
library(flexdashboard)
tiempo_pantalla <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-04-17/tiempo_pantalla.csv")
View(tiempo_pantalla)
#limpieza inicial
tiempo_pantallaSinNA <-na.omit(tiempo_pantalla)
View(tiempo_pantallaSinNA)

# selecciono los primeros 10 personajes con mmás minutos en pantalla
primeros10 <- filter(tiempo_pantallaSinNA, (tiempo_pantallaSinNA$minutos_pantalla>103))
View(primeros10)

#tail(tiempo_pantallaSinNA)
ultimos10 <- filter(tiempo_pantallaSinNA, (tiempo_pantallaSinNA$minutos_pantalla<2.30))
View(ultimos10)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Personajes con más minutos en pantalla

```{r}

p<- ggplot(data=primeros10, aes(x=nombre, y=minutos_pantalla), colour=nombre) + geom_col(aes(fill=nombre))
p +  labs(x = "Personajes", y = "Minutos en Pantalla", colour = " Personajes", 
          title = "",
          subtitle = "Temporada de la 1 a las 64")+  # xlab=""
  theme_classic()+
  theme (axis.text.x = element_blank())+
  theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust=1))+  #los meses se visualizan en forma vertical en el eje x
  theme(plot.title = element_text(family="Courier",
                                  size=rel(1),        #Tama?o relativo de la letra del t?tulo
                                  vjust=2,            #Justificaci?n vertical, para separarlo del gr?fico
                                  position_identity(center),   
                                  face="bold",        #Tipo: Letra negra, otras posibilidades son "plain", "italic", "bold" y "bold.itali
                                  color="black", #Color del t?tulo: maroon, lightblue, lightblue,darkblue, darkorange, black.
                                  lineheight=2.0),  legend.position= "", legend.text = element_blank())
```

Column {data-width=550}
-----------------------------------------------------------------------

### Personajes con menos minutos en pantalla

```{r}
pal <- wes_palette("Darjeeling1", 10, type = "continuous")

p<- ggplot(data=ultimos10, aes(x=nombre, y=minutos_pantalla), colour=nombre) + geom_col(aes(fill=nombre))
p +  labs(x = "Personajes", y = "Minutos en Pantalla", colour = " Personajes", 
          title = "",
          subtitle = "Temporada de la 1 a las 6")+ 
  scale_fill_manual(values=pal)+
  theme_classic()+
  theme (axis.text.x = element_blank())+
  theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust=1))+  #los meses se visualizan en forma vertical en el eje x
  theme(plot.title = element_text(family="Courier",
                                  size=rel(1),        
                                  vjust=2,            
                                  position_identity(center),   
                                  face="bold",      
                                  color="black", 
                              lineheight=2.0),  legend.position= "", legend.text = element_blank())
```

### Chart C

```{r}

```

